/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type NavigationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "navigation";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  siteUrl?: string;
  primaryNav?: NavigationReference;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  items?: Array<{
    label?: InternationalizedArrayString;
    href?: string;
    internalRef?: PostReference | PageReference | CategoryReference;
    _type: "navItem";
    _key: string;
  }>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  body?: InternationalizedArrayBlockContent;
  seoDescription?: InternationalizedArrayText;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type InternationalizedArrayBlockContent = Array<
  {
    _key: string;
  } & InternationalizedArrayBlockContentValue
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: InternationalizedArrayBlockContent;
};

export type Landing = {
  _id: string;
  _type: "landing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  landingImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  ctaText?: InternationalizedArrayString;
  ctaBtnText?: InternationalizedArrayString;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  instagramURL?: string;
  cellNumber?: string;
  email?: string;
  address?: InternationalizedArrayString;
  copyright?: InternationalizedArrayString;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  description?: InternationalizedArrayText;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: InternationalizedArrayBlockContent;
};

export type InternationalizedArrayBlockContentValue = {
  _type: "internationalizedArrayBlockContentValue";
  value?: BlockContent;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | NavigationReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | InternationalizedArrayText
  | InternationalizedArrayString
  | PostReference
  | PageReference
  | CategoryReference
  | Navigation
  | Page
  | InternationalizedArrayBlockContent
  | Slug
  | AuthorReference
  | Post
  | Landing
  | Footer
  | Category
  | BlockContent
  | Author
  | InternationalizedArrayBlockContentValue
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && count(title[_key == $locale && value != null]) > 0]{    "slug": slug.current  }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    "title":       coalesce(title[_key == $locale][0].value, title[0].value),    "body":        coalesce(body[_key == $locale][0].value,  body[0].value),    publishedAt,    mainImage{ asset, alt },    "author": author->{      name,      "slug": slug.current,      image    },    "categories": categories[]->{      "title": coalesce(title[_key == $locale][0].value, title[0].value),      "slug":  slug.current    }  }
export type POST_BY_SLUG_QUERY_RESULT = {
  title: string | null;
  body: BlockContent | null;
  publishedAt: string | null;
  mainImage: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  author: {
    name: string | null;
    slug: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_INDEX_QUERY
// Query: *[_type == "post" && count(title[_key == $locale && value != null]) > 0]    | order(publishedAt desc){    "title":     coalesce(title[_key == $locale][0].value, title[0].value),    "slug":      slug.current,    publishedAt,    mainImage{ asset, alt }  }
export type POSTS_INDEX_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  mainImage: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CATEGORY_SLUGS_QUERY
// Query: *[_type == "category" && count(title[_key == $locale && value != null]) > 0]{    "slug": slug.current  }
export type CATEGORY_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0]{    "title":       coalesce(title[_key == $locale][0].value, title[0].value),    "description": coalesce(description[_key == $locale][0].value, description[0].value),    "slug":        slug.current,    "posts": *[_type == "post" && references(^._id)      && count(title[_key == $locale && value != null]) > 0]      | order(publishedAt desc){      "title":     coalesce(title[_key == $locale][0].value, title[0].value),      "slug":      slug.current,      publishedAt,      mainImage{ asset, alt }    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  slug: string | null;
  posts: Array<{
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
    mainImage: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
  }>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: AUTHOR_SLUGS_QUERY
// Query: *[_type == "author" && defined(slug.current)]{ "slug": slug.current }
export type AUTHOR_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: AUTHOR_BY_SLUG_QUERY
// Query: *[_type == "author" && slug.current == $slug][0]{    name,    "slug": slug.current,    image,    "bio": coalesce(bio[_key == $locale][0].value, bio[0].value),    "posts": *[_type == "post" && references(^._id)      && count(title[_key == $locale && value != null]) > 0]      | order(publishedAt desc){      "title":     coalesce(title[_key == $locale][0].value, title[0].value),      "slug":      slug.current,      publishedAt,      mainImage{ asset, alt }    }  }
export type AUTHOR_BY_SLUG_QUERY_RESULT = {
  name: string | null;
  slug: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  bio: BlockContent | null;
  posts: Array<{
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
    mainImage: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
  }>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && count(title[_key == $locale && value != null]) > 0]{    "slug": slug.current  }
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    "title":          coalesce(title[_key == $locale][0].value, title[0].value),    "body":           coalesce(body[_key == $locale][0].value, body[0].value),    "seoDescription": coalesce(seoDescription[_key == $locale][0].value, seoDescription[0].value),    "slug":           slug.current,    ogImage  }
export type PAGE_BY_SLUG_QUERY_RESULT = {
  title: string | null;
  body: BlockContent | null;
  seoDescription: string | null;
  slug: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    "title":       coalesce(title[_key == $locale][0].value, title[0].value),    "description": coalesce(description[_key == $locale][0].value, description[0].value),    siteUrl,    ogImage,    "primaryNav": primaryNav->{      items[]{        "label": coalesce(label[_key == $locale][0].value, label[0].value),        href,        "internalRef": internalRef->{ _type, "slug": slug.current }      }    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  siteUrl: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  primaryNav: {
    items: Array<{
      label: string | null;
      href: string | null;
      internalRef:
        | {
            _type: "category";
            slug: string | null;
          }
        | {
            _type: "page";
            slug: string | null;
          }
        | {
            _type: "post";
            slug: string | null;
          }
        | null;
    }> | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0]{    instagramURL,    cellNumber,    email,    "address":   coalesce(address[_key == $locale][0].value, address[0].value),    "copyright": coalesce(copyright[_key == $locale][0].value, copyright[0].value)  }
export type FOOTER_QUERY_RESULT = {
  instagramURL: string | null;
  cellNumber: string | null;
  email: string | null;
  address: string | null;
  copyright: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: LANDING_QUERY
// Query: *[_type == "landing"][0]{    "title":       coalesce(title[_key == $locale][0].value, title[0].value),    landingImage{ asset, alt },    image{ asset, alt },    "ctaText":    coalesce(ctaText[_key == $locale][0].value, ctaText[0].value),    "ctaBtnText": coalesce(ctaBtnText[_key == $locale][0].value, ctaBtnText[0].value)  }
export type LANDING_QUERY_RESULT = {
  title: string | null;
  landingImage: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  image: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  ctaText: string | null;
  ctaBtnText: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && count(title[_key == $locale && value != null]) > 0]{\n    "slug": slug.current\n  }\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    "title":       coalesce(title[_key == $locale][0].value, title[0].value),\n    "body":        coalesce(body[_key == $locale][0].value,  body[0].value),\n    publishedAt,\n    mainImage{ asset, alt },\n    "author": author->{\n      name,\n      "slug": slug.current,\n      image\n    },\n    "categories": categories[]->{\n      "title": coalesce(title[_key == $locale][0].value, title[0].value),\n      "slug":  slug.current\n    }\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "post" && count(title[_key == $locale && value != null]) > 0]\n    | order(publishedAt desc){\n    "title":     coalesce(title[_key == $locale][0].value, title[0].value),\n    "slug":      slug.current,\n    publishedAt,\n    mainImage{ asset, alt }\n  }\n': POSTS_INDEX_QUERY_RESULT;
    '\n  *[_type == "category" && count(title[_key == $locale && value != null]) > 0]{\n    "slug": slug.current\n  }\n': CATEGORY_SLUGS_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0]{\n    "title":       coalesce(title[_key == $locale][0].value, title[0].value),\n    "description": coalesce(description[_key == $locale][0].value, description[0].value),\n    "slug":        slug.current,\n    "posts": *[_type == "post" && references(^._id)\n      && count(title[_key == $locale && value != null]) > 0]\n      | order(publishedAt desc){\n      "title":     coalesce(title[_key == $locale][0].value, title[0].value),\n      "slug":      slug.current,\n      publishedAt,\n      mainImage{ asset, alt }\n    }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "author" && defined(slug.current)]{ "slug": slug.current }\n': AUTHOR_SLUGS_QUERY_RESULT;
    '\n  *[_type == "author" && slug.current == $slug][0]{\n    name,\n    "slug": slug.current,\n    image,\n    "bio": coalesce(bio[_key == $locale][0].value, bio[0].value),\n    "posts": *[_type == "post" && references(^._id)\n      && count(title[_key == $locale && value != null]) > 0]\n      | order(publishedAt desc){\n      "title":     coalesce(title[_key == $locale][0].value, title[0].value),\n      "slug":      slug.current,\n      publishedAt,\n      mainImage{ asset, alt }\n    }\n  }\n': AUTHOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "page" && count(title[_key == $locale && value != null]) > 0]{\n    "slug": slug.current\n  }\n': PAGE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    "title":          coalesce(title[_key == $locale][0].value, title[0].value),\n    "body":           coalesce(body[_key == $locale][0].value, body[0].value),\n    "seoDescription": coalesce(seoDescription[_key == $locale][0].value, seoDescription[0].value),\n    "slug":           slug.current,\n    ogImage\n  }\n': PAGE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0]{\n    "title":       coalesce(title[_key == $locale][0].value, title[0].value),\n    "description": coalesce(description[_key == $locale][0].value, description[0].value),\n    siteUrl,\n    ogImage,\n    "primaryNav": primaryNav->{\n      items[]{\n        "label": coalesce(label[_key == $locale][0].value, label[0].value),\n        href,\n        "internalRef": internalRef->{ _type, "slug": slug.current }\n      }\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "footer"][0]{\n    instagramURL,\n    cellNumber,\n    email,\n    "address":   coalesce(address[_key == $locale][0].value, address[0].value),\n    "copyright": coalesce(copyright[_key == $locale][0].value, copyright[0].value)\n  }\n': FOOTER_QUERY_RESULT;
    '\n  *[_type == "landing"][0]{\n    "title":       coalesce(title[_key == $locale][0].value, title[0].value),\n    landingImage{ asset, alt },\n    image{ asset, alt },\n    "ctaText":    coalesce(ctaText[_key == $locale][0].value, ctaText[0].value),\n    "ctaBtnText": coalesce(ctaBtnText[_key == $locale][0].value, ctaBtnText[0].value)\n  }\n': LANDING_QUERY_RESULT;
  }
}
